### ISSUE TITLE
Unable to load transpiler to transpile http://localhost:3000/node_modules/ng-dynamic/index.js

### ISSUE THREAD

**Issue by AliNm14** [laco0416/ng-dynamic#8]
I have installed ng-dynamic but cannot proceed to use. i keep on getting this error in console. could not find any fix. tried to refer in different ways in systemjs.config.js file:
'ng-dynamic':  'npm:ng-dynamic/index.js'
'ng-dynamic':  'node_modules/ng-dynamic/index.js'
'ng-dynamic':  'https://unpkg.com/ng-dynamic@2.0.0/index.js'

whats the issue?

ERROR:
GET http://localhost:3000/traceur 404 (Not Found)
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
	Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:889:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33) [<root>]
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/node_modules/ng-dynamic/index.js
	Error loading http://localhost:3000/node_modules/ng-dynamic/index.js as "ng-dynamic" from http://localhost:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:889:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33) [<root>]
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/node_modules/ng-dynamic/index.js
	Error loading http://localhost:3000/node_modules/ng-dynamic/index.js as "ng-dynamic" from http://localhost:3000/app/app.module.js

**Comment by lacolaco** [comment]
I think it's not an error caused by ng-dynamic. 

> GET http://localhost:3000/traceur 404 (Not Found)

you failed fetching traceur, so you couldn't transpile anything.

**Comment by AliNm14** [comment]
> you failed fetching traceur, so you couldn't transpile anything.

Good answer!!!

**Comment by AliNm14** [comment]
@laco0416  Traceur issue got resolved..Thanks!  Can you provide a working example of DynamicComponentModule or a link to example ?


After traceur issue resolved, I'm getting this error:

Error: (SystemJS) Type DynamicDemoComponent is part of the declarations of 2 modules: SharedModule and AppModule! Please consider moving DynamicDemoComponent to a higher module that imports SharedModule and AppModule. You can also create a new NgModule that exports and includes DynamicDemoComponent then import that NgModule in SharedModule and AppModule.


I tried to solve this by removing 'DynamicDemoComponent' from AppModule declarations. But it again gives this error:

Template parse errors:
Can't bind to 'dynamicComponent' since it isn't a known property of 'div'. ("
    <div [ERROR ->]*dynamicComponent="template; context: {text: text};"></div>
  "): DynamicDemoComponent@1:9

**Comment by rahulbpatel** [comment]
@AliNm14 how did you resolve the Traceur issue?

**Comment by TomBak5** [comment]
@AliNm14  so how to solve traceur issue?

**Comment by wkhutchi** [comment]
I'm getting the same errors, but only after adding "DynamicComponentModule.forRoot({imports: [RouterModule]})," to "@NgModule({  imports: [".  Has anyone found a solution?  And what is the solution?
